// <auto-generated />
using System;
using EventBLib.MarketingDataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventBLib.Migrations.Marketing
{
    [DbContext(typeof(MarketingContext))]
    partial class MarketingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventBLib.Models.MarketingModels.MarkListCard", b =>
                {
                    b.Property<int>("MarkListCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AHref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPayed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PayedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("PaymentAccount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PublicedDue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublicedSince")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShawnQuantity")
                        .HasColumnType("int");

                    b.Property<int>("TirnTrigger")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarkListCardId");

                    b.ToTable("MarkListCards");
                });
#pragma warning restore 612, 618
        }
    }
}
